MODEL:
#  PRETRAIN_PATH: 'transformer_100_sn_90.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'densenet169'
  JPM: True           # original
  RE_ARRANGE: False   # original
  TRAIN_STRATEGY: 'chunk'
#  LR_TYPE: "FT"
#  LR_TYPE: "SN"
  LR_TYPE: "FS"
#  SCHEDULER: 'MultiStepLR'  # the type of division

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  RE: True # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('../../data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 1
  NUM_WORKERS: 4
  P: 8
  K: 2
  NUM_TEST_IMAGES: 4
  NUM_TRAIN_IMAGES: 4

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  SEED: 1151
  MAX_EPOCHS: 121
#  BASE_LR: 0.0001
  BASE_LR: 0.01
  IMS_PER_BATCH: 30
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 20  #
  LOG_PERIOD: 50
  EVAL_PERIOD: 10        #
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
#  GAMMA: 0.7
#  MOMENTUM: 0.7
#  STEPS: None
  LR_DATA_RATIO: 3
  OUT_POINT_FLAG: True
  OUT_POINT_MODEL: "../logs/lr/sn-ep80-bz16/1/transformer_100.pth"
  OUT_POINT_EPOCH: 0
  WARMUP_EPOCHS: 0

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  EPOCH: 120
  WEIGHT: '../logs/lr/sn-ep80-bz16/1'

OUTPUT_DIR: '../logs/lr/fs-ep80-bz16'


